// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionTab: typeof import('./src/components/ActionTab.vue')['default']
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    CloudList: typeof import('./src/components/CloudList.vue')['default']
    CorrectionSong: typeof import('./src/components/CorrectionSong.vue')['default']
    ExtLink: typeof import('./src/components/ExtLink.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    UploadSong: typeof import('./src/components/UploadSong.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}

export { }
